import { sha256 } from "./hash-v2.js";
import { createLauncherParityProject, saveLauncherParityProject } from "./parity-history-v1.js";
// prettier-ignore
import { ParityFormatRefusalError, type LauncherParityProjectV1, type MigrationDecisionV1, type MigrationFieldV1 } from "./parity-model-v1.js";
export type MigrationDecisionsV1 = Partial<Record<MigrationFieldV1, MigrationDecisionV1>>;
// prettier-ignore
export type MigrationResultV1 = { sourceBytes: string; sourceHash: string; formatVersion: 1 | 2; candidate: LauncherParityProjectV1; requiresConfirmation: MigrationFieldV1[] };
// prettier-ignore
const object = (value: unknown): Record<string, unknown> => value && typeof value === "object" ? value as Record<string, unknown> : {};
// prettier-ignore
const field = (project: Record<string, unknown>, tokens: Record<string, unknown>, key: string) => project[key] ?? tokens[key];
const legacyFields: MigrationFieldV1[] = ["accent", "background", "foreground", "scenes", "transition"];
// prettier-ignore
export function migrateLegacyMaterial(source: string | Record<string, unknown>, decisions: MigrationDecisionsV1 = {}): MigrationResultV1 { const sourceBytes = typeof source === "string" ? source : JSON.stringify(source); let parsed: unknown; try { parsed = JSON.parse(sourceBytes); } catch { throw new ParityFormatRefusalError("invalid-json", "Legacy project bytes are not valid JSON."); } const project = object(parsed), formatVersion = project.formatVersion; if (formatVersion !== 1 && formatVersion !== 2) throw new ParityFormatRefusalError("unsupported-format", `Unsupported legacy format: ${String(formatVersion)}`); const metadata = object(project.metadata), tokens = object(project.tokens), material = object(project.material), primaryColor = field(material, tokens, "primaryColor") ?? project.primaryColor, accent = field(project, tokens, "accent"), darkTheme = field(material, tokens, "darkTheme") ?? project.darkTheme, needs: MigrationFieldV1[] = []; if (primaryColor === undefined && !(decisions.accent === "map-primary-color" && isRgb(accent))) needs.push("primaryColor"); if (typeof darkTheme !== "boolean") needs.push("darkTheme"); for (const key of legacyFields) { const present = key === "scenes" ? Array.isArray(project.scenes) && project.scenes.length > 0 : key === "transition" ? project.launchTransition !== undefined || project[key] !== undefined : field(project, tokens, key) !== undefined; if (present && !decisions[key]) needs.push(key); } const mappedColor = isRgb(primaryColor) ? primaryColor : decisions.accent === "map-primary-color" && isRgb(accent) ? accent : { r: 0, g: 0, b: 0 }; const candidate = createLauncherParityProject({ projectId: typeof project.projectId === "string" ? project.projectId : `migrated-${sha256(sourceBytes).slice(0, 12)}`, metadata: { name: String(metadata.name ?? "Migrated theme"), description: String(metadata.description ?? "Migrated Material theme"), author: String(metadata.author ?? "Unknown") }, primaryColor: mappedColor, darkTheme: typeof darkTheme === "boolean" ? darkTheme : false }); candidate.evidence.legacy = { sourceHash: sha256(sourceBytes), sourceBytes, formatVersion, mappings: { ...decisions }, exclusions: legacyFields.filter((key) => decisions[key] && decisions[key] !== "map-primary-color") }; return { sourceBytes, sourceHash: candidate.evidence.legacy.sourceHash, formatVersion, candidate, requiresConfirmation: [...new Set(needs)] }; }
// prettier-ignore
export function saveMigratedParityProject(result: MigrationResultV1): string { if (result.requiresConfirmation.length) throw new ParityFormatRefusalError("invalid-format", `Migration decisions required: ${result.requiresConfirmation.join(", ")}`); return saveLauncherParityProject(result.candidate); }
// prettier-ignore
const isRgb = (value: unknown): value is { r: number; g: number; b: number } => { const color = value as { r?: unknown; g?: unknown; b?: unknown } | null; return Boolean(color && [color.r, color.g, color.b].every((component) => Number.isInteger(component) && Number(component) >= 0 && Number(component) <= 255)); };
export { ParityFormatRefusalError as MigrationRefusalError };
